#!/system/bin/sh

# Reboot glasses service to pick up menu entry.

DEVICE=$(getprop ro.product.device)

if [[ $DEVICE == *"wm170_gls"* ]]; then
  GLASSES_SERIVCE="dji.glasses_wm150_service"
else
  GLASSES_SERIVCE="dji.glasses_service"
fi

IS_GLASSES_RUNNING=$(getprop $GLASSES_SERIVCE)
if [[ $IS_GLASSES_RUNNING -eq 1 ]]; then
  setprop $GLASSES_SERIVCE 0
  sleep 3
  setprop $GLASSES_SERIVCE 1
  sleep 3
fi
